version: '3'
services:
  bot:
    build: ./
    container_name: eula-bot
    restart: on-failure
    environment: 
      REDIS_HOST: redis
      DB_HOST: mysql
      DOCKER_ENV: "DOCKER"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
  redis:
    container_name: redis
    image: redis:6.2
  mysql:
    image: jsurf/rpi-mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
