version: '3'
services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis_dev
    ports:
      - 8090:8081
    depends_on:
      - redis_dev
  redis:
    container_name: redis
    image: redis:alpine
    ports: 
      - "6379:6379"
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

